### ISSUE TITLE
mdjfqsdf

### ISSUE THREAD

**Issue by VincentSchippefilt** [odoo/o-spreadsheet#1804]

**Comment by pro-odoo** [comment]
Hello @VincentSchippefilt,

Thank you for your interest in o-spreadsheet.

Can you give us more information about your issue ?

Thanks in advance,

The spreadsheet team

**Comment by VincentSchippefilt** [comment]
> Hello @VincentSchippefilt,
> 
> Thank you for your interest in o-spreadsheet.
> 
> Can you give us more information about your issue ?
> 
> Thanks in advance,
> 
> The spreadsheet team

no :stuck_out_tongue:
