### ISSUE TITLE
a Chinese Character Input Method is not support

### ISSUE THREAD

**Issue by hongfeizhou** [odoo/o-spreadsheet#1881]
when i use  Chinese Character Input Method like sougou, it doesn't work

**Comment by rrahir** [comment]
Hi @hongfeizhou , could you provide a demonstration of your problem and specify in which version you are experiencing this issue ?

We recently addressed something quite similar reported by a japanese in #1779 . However this only applies to versions 15.0 and above. Are you using a version prior to 15.0? If not, could you provide a step-by-step way to reproduce your issue ?


Thanks in advance and thank you for taking interest in the development of this app :)

**Comment by rrahir** [comment]
Update: I am now able to relaintly reproduce the bug. we will investigate it as soon as possible !

**Comment by rrahir** [comment]
Fixed in https://github.com/odoo/o-spreadsheet/pull/3456
