### ISSUE TITLE
Charts: how to add new type

### ISSUE THREAD

**Issue by dberardo-com** [odoo/o-spreadsheet#3246]
in particular i would like to add a radar chart https://www.chartjs.org/docs/latest/charts/radar.html

which file(s) should be edited for it to happen ? i guess chart_factory.ts

**Comment by dberardo-com** [comment]
also as a bonus question: can a formula output a chart ? 

example: https://peltiertech.com/chart-series-formula/

**Comment by hokolomopo** [comment]
Hello 👋 Sorry for the tardy answer.

To create a new chart type, you need mutliple parts:

- An implementation of `AbstractChart`. [Bar chart for example](https://github.com/odoo/o-spreadsheet/blob/17.0/src/helpers/figures/charts/bar_chart.ts)
- Then you can add the implementation to the [chartRegistry](https://github.com/odoo/o-spreadsheet/blob/c2eed35cb258ae0de1c7cc386ece59053d973c0b/src/registries/chart_types.ts#L70)
- You also need a component that draw the chart, and add it to the [chartComponentRegistry](https://github.com/odoo/o-spreadsheet/blob/c2eed35cb258ae0de1c7cc386ece59053d973c0b/src/registries/chart_types.ts#L151)
- Finally you need side panel components to edit your chart, that you add to the [chartSidePanelComponentRegistry](https://github.com/odoo/o-spreadsheet/blob/c2eed35cb258ae0de1c7cc386ece59053d973c0b/src/components/side_panel/chart/index.ts#L30)

I hope it helps. We unfortunately don't have a comprehensive documentation for that yet.

For your bonus questions: 
- a formula cannot output a chart no. We have no plans on implementing that in the near future.
- Scatter plots are now available in the latest versions. We also plan on impelmenting other new chart types within the year.

Have a nice day 👋

**Comment by dberardo-com** [comment]
tahnks for the reply:

> a formula cannot output a chart no. We have no plans on implementing that in the near future.

i assume i could do this by using a model.dispatch() call to specifically create a new chart in the model right ? i believe this could be enough for my use case --> as long as i can then reference the same chart from the formula to perform update / delete operations

> To create a new chart type, you need mutliple parts:

is the current structure specific of chartjs library or can i change the underlying charting library for the new custom charts  ?

**Comment by hokolomopo** [comment]
> i assume i could do this by using a model.dispatch() call to specifically create a new chart in the model right ? i believe this could be enough for my use case --> as long as i can then reference the same chart from the formula to perform update / delete operations

Unfortunately it won't be so simple, because in our design model.dispatch() cannot be used during the evaluation (because it might trigger infinite loops of dispatch => evaluation => dispatch). You can probably make it work by having your function creating an async callback that will trigger the necessary dispatch. I cannot really help you with that.

> is the current structure specific of chartjs library or can i change the underlying charting library for the new custom charts ?

ChartJS isn't necessarry 🙂 [Scorecards](https://github.com/odoo/o-spreadsheet/blob/17.0/src/components/figures/chart/scorecard/chart_scorecard.ts) for example simply draw on a canvas, and were pure HTML in previous versions.

**Comment by dberardo-com** [comment]
> Unfortunately it won't be so simple, because in our design model.dispatch() cannot be used during the evaluation (because it might trigger infinite loops of dispatch => evaluation => dispatch). You can probably make it work by having your function creating an async callback that will trigger the necessary dispatch. I cannot really help you with that.

i am already using dispatch in this use case: https://github.com/odoo/o-spreadsheet/issues/1935 ("EVALUATE_CELLS") -- i assume this won't be any different, right ? is there a command for creating/updating/deleting charts ?

> ChartJS isn't necessary🙂 [Scorecards](https://github.com/odoo/o-spreadsheet/blob/17.0/src/components/figures/chart/scorecard/chart_scorecard.ts) for example simply draw on a canvas, and were pure HTML in previous versions.

lovely, i will try out D3 based libraries, such as plotly e.g.

**Comment by hokolomopo** [comment]
You can have a look at the commands handled by the `ChartPlugin` (`plugins.core/charts.ts`) to interact with the chart.

Note that your original question was on radar charts, and those are parts of our roadmap so we will implement them sometime before October (hopefully).  

Have a nice day :wave:

**Comment by dberardo-com** [comment]
thanks for answering, i will have a look.
as for the radar chart, i have some custom implementation needs, in particular i have the need of a radar chart for plotting degrees (from 0 to 360) in order to show the angular direction of signals. and also i need to represent multiple series on it, similar to this: https://echarts.apache.org/examples/en/editor.html?c=radar2

thats why i believe i might need to go for a custom implementation
