### ISSUE TITLE
enable input or display multiline text

### ISSUE THREAD

**Issue by linwinfan** [odoo/o-spreadsheet#3604]
**Is your feature request related to a problem? Please describe.**
Current cannot input or display multiline text in a cell

**Describe the solution you'd like**
enable input and display multiline text

**Comment by hokolomopo** [comment]
Hello,

As far as I can tell we already support this feature (alt + enter or ctrl+ enter while editing a cell, you can test this on our [playground](https://odoo.github.io/o-spreadsheet/)).

Is there some issue on your end where the feature won't work ? Or is there a specific use case that we do not support ? 

Regards
