### ISSUE TITLE
Spreadsheet  right-to-left  layout support

### ISSUE THREAD

**Issue by abbasEbadian** [odoo/o-spreadsheet#3612]
**Is your feature request related to a problem? Please describe.**
Currently just LTR direction is available for sheet layout .
For Arabic and Persian languages, RTL layout is needed.

**Describe the solution you'd like**
Add a toggle RTL button in toolbar.

**Additional context**
Microsoft Excel example:
![21fa9c06-d1aa-4bbf-9c1e-e7b607be26f0](https://github.com/odoo/o-spreadsheet/assets/16752051/a7c2054f-4aad-4aff-8da3-cd8d3dd65cd4)

**Comment by VincentSchippefilt** [comment]
Hello,
While I agree that RTL is useful for a part of the population, the amount of work required to make this work **well** far outweigh it's gain.
I do not plan to develop this in the foreseeable future.
