### ISSUE TITLE
getter to get currently selected coordinates

### ISSUE THREAD

**Issue by dberardo-com** [odoo/o-spreadsheet#3891]
is it possible to get the currently selected coordinates as in (A2:C4)?

or is it possible to convert zones to coordinates, example getters.getActivePosition() --> "A2" ?

**Comment by hokolomopo** [comment]
Hello,

You can use the getter `zoneToXC`

```js
  const sheetId = model.getters.getActiveSheetId();
  const selection = model.getters.getSelectedZone();
  console.log(model.getters.zoneToXC(sheetId, selection)); // => "A2:C4"
```

Have a nice day 👋

**Comment by hokolomopo** [comment]
Hello 👋 

There is no getter that directly take the XC as argument, but you can convert the XC to `{col , row}` coordinates with the `toCartesian` helper, then use the getter `getCell`
