### ISSUE TITLE
diagrams: invert xaxis

### ISSUE THREAD

**Issue by dberardo-com** [odoo/o-spreadsheet#4365]
very often i am using spreadsheets to visualize temporal data. as humans we think from top to bottom, so today would be on top and 7 days ago would be on the bottom.

but this is hard to visualize in the spreadsheet becasue (as of version 16) there is no x-axis inversion option and i end up with an spreadsheet that look like this:

![image](https://github.com/odoo/o-spreadsheet/assets/65530457/6f77aea7-c027-4193-bcd6-2bee31aab70e)

bu then a diagram that looks like this:

![image](https://github.com/odoo/o-spreadsheet/assets/65530457/595af382-9cbc-4f78-afc8-212fe4a35fe0)

where you can of course see that the x-axis should go from left to right and not viceversa.

**Comment by VincentSchippefilt** [comment]
Hello,
Thank you for your feedback. 
This use-case is valid, however it can easily be solved by sorting your data range. 
I do not want to complexify the configuration of charts any more than **absolutely** necessary.
