### ISSUE TITLE
running v17.3.3 gives mounting error

### ISSUE THREAD

**Issue by dberardo-com** [odoo/o-spreadsheet#4485]
i have already succesfully  run v17.0.3 but i am now trying with v17.3.3 and get this owl runtime error:

Caused by: TypeError: Cannot read properties of undefined (reading 'bind')
    at Grid.template (eval at compile (@odoo_owl.js?v=56824602:4761:12), <anonymous>:27:416)
    at Fiber._render (@odoo_owl.js?v=56824602:1547:26)
    at Fiber.render (@odoo_owl.js?v=56824602:1539:10)
    at ComponentNode.initiateRender (@odoo_owl.js?v=56824602:1999:13)

happening at this line of code: 

![image](https://github.com/odoo/o-spreadsheet/assets/65530457/c6372d3e-0298-458a-9492-23e34630021c)

if i remove the <GridOverlay> component from the template.xml then the app renders, but without any grid.

what am i doing wrong ?

**Comment by dberardo-com** [comment]
,... ok i forgot to run the build command again, so i was using a previous version of the template.xml file ...

**Comment by dberardo-com** [comment]
however, i get a very nasty error when trying to displaying chart data : 
![image](https://github.com/odoo/o-spreadsheet/assets/65530457/5c04a280-46c6-432b-8592-b01427cb456d)



this error is also within the live demo: https://odoo.github.io/o-spreadsheet/ --> click on "Chart"

**Comment by dberardo-com** [comment]
i also get the same error when trying to inlcude a new pivot table in the demo.

also including a  checkbox, the whole app crashes ...

**Comment by hokolomopo** [comment]
Hello :slightly_smiling_face: 

Thanks for the report ! There was indeed a problem that charts were breaking if no translation method was set. This will be fixed in https://github.com/odoo/o-spreadsheet/pull/4497

Feel free to re-open the issue if the bug is not fixed after the PR is merged.

Have a nice dayy :wave:

**Comment by dberardo-com** [comment]
hi there. i am still struggling very much understanding how versioning works on this project. i have seen that you have open a PR from the 17.0 version but ia was referring to the 17.3.3 ... are you changes compatible with that branch and can i simply merge you PR into my local repo which is checked out on the 17.3.3 ?

very confusing for me :-/

**Comment by hokolomopo** [comment]
Hello 👋 

Our versionning is based on Odoo's. We release a stable version every few months (17.0, 17.1, 17.2, ...). In principle, these versions are frozen and should not contain new major changes. The only time they should be modified are for bugfixes. Minor versions 17.3.1, 17.3.2, ... are the base 17.3 + some bugfixes. 

And bugfixes done in a major version are forward-ported to every subsequent major version. So the commit in my PR in 17.0 once merged will be cherry-picked in 17.1, 17.2, 17.3, and master.

Hope it helps 👋

**Comment by dberardo-com** [comment]
ok great, so i might cherry pick your changes in my forked 17.3.3 repo or would you recommend to wait for the official release? i mean, is the cherry pick as straight forward as copying all changes over to my repo or should some code be adapted to the new 17.3.3 version ?

**Comment by hokolomopo** [comment]
> ok great, so i might cherry pick your changes in my forked 17.3.3 repo or would you recommend to wait for the official release? i mean, is the cherry pick as straight forward as copying all changes over to my repo or should some code be adapted to the new 17.3.3 version ?

You can cherry-pick the commit if you want, I don't think this particular commit will conflict with anything. As a general rule I'd recommand rebasing on the branch saas-17.3 to get the latest fixes. The PR should be merged within the week.
