### ISSUE TITLE
possibility to use formulas also in case of errors

### ISSUE THREAD

**Issue by dberardo-com** [odoo/o-spreadsheet#4526]
i have got this situation and would like to create a sum function that can ignore #ERROR cells:

![image](https://github.com/odoo/o-spreadsheet/assets/65530457/72b3a1f7-3480-4d11-ae8f-661176520e9e)

as in =MY_SUM(A1:A6) --> return sum ignoring #ERROR cells

is this possible at the moment ?

**Comment by hokolomopo** [comment]
Hello :wave: 

It is now possible ! See [my comment](https://github.com/odoo/o-spreadsheet/issues/5219#issuecomment-2490324658) on your other issue.

Now the arguments of the functions are  `{ value: CellValue; format?: Format; message?: string  }` object. You can just ignore arguments that have a `message` (errorMessage) in your custom SUM, and you should be good to go
