### ISSUE TITLE
ODOO.CURRENCY.RATE with company as an optional argument

### ISSUE THREAD

**Issue by jok-adhoc** [odoo/o-spreadsheet#4691]
In some cases, specially where the currency is not stable, companies work with a company using its local currency and another with a hard currency, like USD. This is a reason why ODOO.CURRENCY.RATE might be used on financial reports.

So now, sometimes the currency rate is not the same from 1 to 2 as from 2 to 1. For example in Argentina, where multiple currency rates are used (Official rate, CCL, MEP, etc). This causes the creation of a new currencies depending on the rate that must be used in each operation. 

Imagine we have:

- Company1: Currency USD
- Company2: Currency ARS
- A report in USD is needed

The rate USD/ARS is the official rate, but for some operations or in order to report them in a "liquid" rate, Company2 needs to calculate them with USDCCL (and keeping the USD/ARS with the official rate)

**Current situation**
They must create two different currencies, one for each company, and keep them both up to date, because depending on which company you are, spreadsheet shows its rate.

**What do we expect?**
To have the argument [company] in order to set it up. This would cause the update for just one currency, the USDCCL in Company2

**Comment by rrahir** [comment]
Hello ! 
Thanks for your interest. I will notify our product owner of your request and we will let you know how we plan to handle this case.

For future feature requests that are strictly Odoo related, it would be most effective address them directly to feedback@odoo.com so that the product owner can directly consider it.

Have a lovely day

**Comment by jok-adhoc** [comment]
Lovely to see this, thanks a lot @LucasLefevre @rrahir
